USE [master]
GO

/****** Object:  Database [BW2Discovery]    Script Date: 29/08/2023 15:03:15 ******/
CREATE DATABASE [BW2Discovery]
 CONTAINMENT = PARTIAL
 ON  PRIMARY 
( NAME = N'BW2Discovery', FILENAME = N'E:\Databases\BW2Discovery.mdf' , SIZE = 255597248KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'BW2Discovery_log', FILENAME = N'E:\DatabasesLogs\BW2Discovery_log.ldf' , SIZE = 37712192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BW2Discovery].[dbo].[sp_fulltext_database] @action = 'disable'
end
GO

ALTER DATABASE [BW2Discovery] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BW2Discovery] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BW2Discovery] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BW2Discovery] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BW2Discovery] SET ARITHABORT OFF 
GO

ALTER DATABASE [BW2Discovery] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BW2Discovery] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BW2Discovery] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BW2Discovery] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BW2Discovery] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BW2Discovery] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BW2Discovery] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BW2Discovery] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BW2Discovery] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BW2Discovery] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BW2Discovery] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BW2Discovery] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BW2Discovery] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BW2Discovery] SET ALLOW_SNAPSHOT_ISOLATION ON 
GO

ALTER DATABASE [BW2Discovery] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BW2Discovery] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BW2Discovery] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BW2Discovery] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [BW2Discovery] SET  MULTI_USER 
GO

ALTER DATABASE [BW2Discovery] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BW2Discovery] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BW2Discovery] SET DEFAULT_FULLTEXT_LANGUAGE = 1033 
GO

ALTER DATABASE [BW2Discovery] SET DEFAULT_LANGUAGE = 1033 
GO

ALTER DATABASE [BW2Discovery] SET NESTED_TRIGGERS = ON 
GO

ALTER DATABASE [BW2Discovery] SET TRANSFORM_NOISE_WORDS = OFF 
GO

ALTER DATABASE [BW2Discovery] SET TWO_DIGIT_YEAR_CUTOFF = 2049 
GO

ALTER DATABASE [BW2Discovery] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BW2Discovery] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [BW2Discovery] SET DELAYED_DURABILITY = FORCED 
GO

ALTER DATABASE [BW2Discovery] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [BW2Discovery] SET QUERY_STORE = OFF
GO

ALTER DATABASE [BW2Discovery] SET  READ_WRITE 
GO


